name: gistbin
version: git
summary: GitHub Gist command line client
description: |
  Upload code snippets and command output via the command line.
base: core18
confinement: strict

parts:
  gistbin:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - certifi == 2020.6.20
      - chardet == 3.0.4
      - idna == 2.10
      - RandomWords == 0.3.0
      - requests == 2.24.0
      - urllib3 == 1.25.10
  
apps:
  gistbin:
    command: bin/gistbin


plugs:
  gistbin-home:
    interface: home
  gistbin-network:
    interface: network